### ISSUE TITLE
Add ability to Archive customers

### ISSUE THREAD

**Issue by sanderdejong88** [FrontMen/fm-hours#52]
Use end date instead of boolean.
Have a look at Reports.
Allow filtering on Customers page

**Comment by mmehmetAliIzci** [comment]
Questions:

- The title says `add ability to archive customers`. We already have "Delete" in place. Does this mean we want to add another state, which is "archived" ? Which doesn't deletes it but only de-activates it and employee's are not be able to be the assigned to archived customers.

- `Have a look at Reports`. I assume this means we want to get a report of who've worked on this customer for how long ?

- `Use end date instead of boolean`. I assume this means we want to save both "archived" and "archived date" ?

- `Allow filtering on Customers page` Does this mean we want to have the functionality to filter by "archived" or not. Or do we also want to filter by: "archived date", "name", "debtor"
